<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.7.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Gertjan Verhoeven">

  
  
  
    
  
  <meta name="description" content="This blog post is about the Roche Rapid Antigen Test Nasal. How accurate is it? I tracked down the data mentioned in the kit&#39;s leaflet, discuss the whole measurement process and used R to reproduce the sensitivity and specificity of the test.">

  
  <link rel="alternate" hreflang="en-us" href="/post/covid_antigen_test_reliability/">

  


  
  
  
  <meta name="theme-color" content="#2962ff">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  





<script async src="https://www.googletagmanager.com/gtag/js?id=G-GQH76F5Q5R"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
      dataLayer.push(arguments);
  }

  function trackOutboundLink(url) {
    gtag('event', 'click', {
         'event_category': 'outbound',
         'event_label': url,
         'transport_type': 'beacon',
         'event_callback': function () {
           document.location = url;
         }
    });
    console.debug("Outbound link clicked: " + url);
  }

  function onClickCallback(event) {
    if ((event.target.tagName !== 'A') || (event.target.host === window.location.host)) {
      return;
    }
    trackOutboundLink(event.target);  
  }

  gtag('js', new Date());
  gtag('config', 'G-GQH76F5Q5R', {});

  
  document.addEventListener('click', onClickCallback, false);
</script>


  


  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="/post/covid_antigen_test_reliability/">

  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@GertjanVerhoev1">
  <meta property="twitter:creator" content="@GertjanVerhoev1">
  
  <meta property="og:site_name" content="Gertjan Verhoeven">
  <meta property="og:url" content="/post/covid_antigen_test_reliability/">
  <meta property="og:title" content="Using R to analyse the Roche Antigen Rapid Test: How accurate is it? | Gertjan Verhoeven">
  <meta property="og:description" content="This blog post is about the Roche Rapid Antigen Test Nasal. How accurate is it? I tracked down the data mentioned in the kit&#39;s leaflet, discuss the whole measurement process and used R to reproduce the sensitivity and specificity of the test."><meta property="og:image" content="/img/headers/covid_antigen_test.png">
  <meta property="twitter:image" content="/img/headers/covid_antigen_test.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2021-06-06T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2021-06-06T00:00:00&#43;00:00">
  

  


    






  






<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "/post/covid_antigen_test_reliability/"
  },
  "headline": "Using R to analyse the Roche Antigen Rapid Test: How accurate is it?",
  
  "datePublished": "2021-06-06T00:00:00Z",
  "dateModified": "2021-06-06T00:00:00Z",
  
  "author": {
    "@type": "Person",
    "name": "Gertjan Verhoeven"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Gertjan Verhoeven",
    "logo": {
      "@type": "ImageObject",
      "url": "img//"
    }
  },
  "description": "This blog post is about the Roche Rapid Antigen Test Nasal. How accurate is it? I tracked down the data mentioned in the kit's leaflet, discuss the whole measurement process and used R to reproduce the sensitivity and specificity of the test."
}
</script>

  

  


  


  





  <title>Using R to analyse the Roche Antigen Rapid Test: How accurate is it? | Gertjan Verhoeven</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  

<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Gertjan Verhoeven</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Gertjan Verhoeven</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#about"><span>Home</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact"><span>Contact</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      <li class="nav-item">
        <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
      </li>
      

      

    </ul>

  </div>
</nav>


  <article class="article">

  









<div class="article-header">
  
  
  <img src="/img/headers/covid_antigen_test.png" class="article-banner" alt="">
  

  
</div>




  

  
  
  
<div class="article-container pt-3">
  <h1>Using R to analyse the Roche Antigen Rapid Test: How accurate is it?</h1>

  

  
    


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    Jun 6, 2021
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    19 min read
  </span>
  

  
  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/categories/statistics-r-measurement/">Statistics, R, Measurement</a></span>
  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style">
      
<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p><em>(Image is from a different antigen test)</em></p>
<p>Many people are suspicious about the reliability of rapid self-tests, so I decided to check it out.
For starters, I LOVE measurement. It is where learning from data starts, with technology and statistics involved.
With this post, I’d like to join the swelling ranks of amateur epidemiologists :) I have spent a few years in a molecular biology lab, that should count for something right?</p>
<p>At home, we now have a box of the <strong>SARS-CoV-2 Rapid Antigen Test Nasal</strong> kit.
The kit is distributed by Roche, and manufactured in South Korea by a company called SD Biosensor.</p>
<p>So how reliable is it? A practical approach is to compare it to the golden standard, the PCR test, that public health test centers use to detect COVID-19. Well, the leaflet of the kit describes three experiments that do exactly that!
So I tracked down the data mentioned in the kit’s leaflet, and decided to check them out.</p>
<p>But before we analyze the data, you want to know how they were generated, right? RIGHT?
For this we use cause-effect diagrams (a.k.a. DAGs), which we can quickly draw using <a href="http://dagitty.net">DAGitty</a>.</p>
<div id="a-causal-model-of-the-measurement-process" class="section level1">
<h1>A causal model of the measurement process</h1>
<p>The cool thing about DAGitty is that we can use a point-n-click interface to draw the diagram, and then export code that contains an exact description of the graph to include in R. (You can also view the <a href="http://dagitty.net/dags.html?id=whqGBx">graph for this blog post at DAGitty.net</a>):</p>
<p><img src="/post/2021_05_14_covid_rapid_test_reliability_files/figure-html/unnamed-chunk-2-1.png" width="768" /></p>
<p>The graph is based on the following description of the various cause-effect pairs:</p>
<p>It all starts with whether someone is infected. After infection, virus particles start to build up. These particles can be in the lungs, in the throat, nose etc.
These particles either do or do not cause symptoms. Whether there are symptoms will likely influence the decision to test, but there will also be people without symptoms that will be tested (i.e. if a family member was tested positive).</p>
<p>In the experiments we analyze, two samples were taken, one for the PCR test and one for the antigen test. The way the samples were taken differed as well: “shallow” nose swabs for the rapid antigen test, and a combination of “deep” nose and throat swabs for the PCR test.</p>
<p>Now that we now a bit about the measurement process, lets look at how the accuracy of the antigen test is quantified.</p>
</div>
<div id="quantifying-the-accuracy-of-an-covid-19-test" class="section level1">
<h1>Quantifying the accuracy of an COVID-19 test</h1>
<p>The PCR test result serves as the ground truth, the standard to which the antigen test is compared.
Both tests are binary tests, either it detects the infection or it does not (to a first approximation).</p>
<p>For this type of outcome, two concepts are key: the <strong>sensitivity</strong> (does the antigen test detect COVID when the PCR test has detected it) and <strong>specificity</strong> of the test (does the antigen test ONLY detect COVID, or also other flu types or even unrelated materials, for which the PCR test produces a negative result).</p>
<p>The leaflet contains information on both.</p>
<ul>
<li>Sensitivity 83.3% (95%CI: 74.7% - 90.0%)</li>
<li>Specificity 99.1% (95%CI: 97.7% - 99.7%)</li>
</ul>
<p>But what does this really tell us? And where do these numbers come from?</p>
<p>Before we go to the data, we first need to know a bit more detail on what we are actually trying to measure, the viral load, and what factors influence this variable.</p>
</div>
<div id="viral-load-as-target-for-measurement" class="section level1">
<h1>Viral load as target for measurement</h1>
<p>So, both tests work by detecting viral particles in a particular sample. The amount of virus particles present in the sample depends on, among others:</p>
<ul>
<li>Time since infection</li>
<li>How and where the sample is taken (throat, nose, lungs, using a swab etc)</li>
</ul>
<p>I’ll discuss both.</p>
<div id="time-since-infection" class="section level2">
<h2>Time since infection</h2>
<p>When you have just been infected, your body will contain only a small amount of virus.
The <strong>viral load</strong> is a function of time since infection, because it takes time for the virus to multiply itself. Even PCR cannot detect an infection on the first day, and even after 8 days, there are still some 20% of cases that go undetected by PCR (presumably because the amount of viral particle is too low) (Ref: Kucirka et al 2020).</p>
<p>If you want to know more about the ability of PCR to detect COVID infections go check out <a href="https://github.com/HopkinsIDD/covidRTPCR">the covidRTPCR Github repository</a>. It is completely awesome, with open data, open code, and Bayesian statistics using <a href="https://mc-stan.org/">Stan</a>!</p>
</div>
<div id="how-and-where-the-sample-is-taken" class="section level2">
<h2>How and where the sample is taken</h2>
<p>There are many ways to obtain a sample from a person.</p>
<p>Here the golden standard is a so-called <strong>Nasopharyngeal swab</strong>. This goes through your nose all the way (~ 5 cm) into the back of the throat, and is highly uncomfortable. Typically, only professional health workers perform <strong>nasopharyngeal</strong> swabs.
In these experiments, this deep nose swab was combined with a swab from the throat (<strong>oroharyngeal</strong>). This is also how test centers in the Netherlands operated during the last year.</p>
<p>There are various alternatives: We have spit, saliva, we can cough up “sputum” (slime from the lungs) or we can take swab from the front part of the nose (“nasal”).</p>
<p>The Roche antigen test is a <strong>nasal</strong> test that only goes up to 2 cm in the nose and can be used by patients themselves (“self-collected”).</p>
</div>
</div>
<div id="the-dataset-results-from-the-three-berlin-studies" class="section level1">
<h1>The dataset: results from the three Berlin studies</h1>
<p>Now that we have some background info, we are ready to check the data!</p>
<p>As mentioned above, this data came from three experiments on samples from in total 547 persons.</p>
<p>After googling a bit, I found out that the experiments were performed by independent researchers in a famous University hospital in Berlin, <a href="https://de.wikipedia.org/wiki/Charit%C3%A9">Charité</a>. After googling a bit more and mailing with one of the researchers involved, Prof. Andreas Lindner, I received a list of papers that describe the research mentioned in the leaflet (References at the end of this post).</p>
<p>The dataset for the blog post compares <strong>nasal</strong> samples tested with the Roche Antigen test kit, to PCR-tested <strong>nasopharyngeal</strong> plus <strong>oropharyngeal</strong> samples taken by professionals.</p>
<p><strong>This blog post is possible because the three papers by Lindner and co-workers all contain the raw data as a table in the paper. Cool!</strong>
Unfortunately, this means the data is not <strong>machine readable</strong>. However, with a combination of manual tweaking / find-replace and some coding, I tidied the data of the three studies into a single <code>tibble</code> data frame. You can grab the code and data from my <a href="https://github.com/gsverhoeven/hugo_source/tree/master/content/post/sars_test">Github</a>.</p>
<pre class="r"><code># creates df_pcr_pos
source(&quot;sars_test/dataprep_roche_test.R&quot;)

# creates df_leaflet
source(&quot;sars_test/dataprep_roche_test_leaflet.R&quot;)

# see below
source(&quot;sars_test/bootstrap_conf_intervals.R&quot;)</code></pre>
<p>The dataset <code>df_pcr_pos</code> contains, for each <strong>PCR positive</strong> patient:</p>
<ul>
<li><code>ct_value</code></li>
<li><code>viral_load</code></li>
<li><code>days_of_symptoms</code></li>
<li><code>mm_value</code> (Result of the antigen test measurement, 1 is positive, 0 is negative)</li>
</ul>
<p>To understand the PCR data, we need to know a bit more about the PCR method.</p>
<div id="the-pcr-method" class="section level2">
<h2>The PCR method</h2>
<p>The PCR method not only measures <strong>if</strong> someone is infected, it also provides an estimate of the viral load in the sample.
How does this work? PCR can amplify, in so-called cycles, really low quantities of viral material in a biological sample. The amount of cycles of the PCR device needed to reach a threshold of signal is called the cycle threshold or <strong>Ct value</strong>. The less material we have in our sample, the more cycles we need to amplify the signal to reach a certain threshold.</p>
<p>Because the amplification is an exponential process, if we take the log of the number of virus particles, we get a linear inverse (negative) relationship between <strong>ct_value</strong> and <strong>viral_load</strong>. For example, <span class="math inline">\(10^6\)</span> particles is a viral load of 6 on the log10 scale.</p>
<p>So let’s plot the <code>ct_value</code> of the PCR test vs the <code>viral_load</code>:</p>
<pre class="r"><code>set.seed(123)
ggplot(df_pcr_pos, aes(x = ct_value, y = viral_load, color = factor(pcr_assay_type))) + 
  geom_point() + ggtitle(&quot;Calibration curves for viral load (log10 scale)&quot;)</code></pre>
<p><img src="/post/2021_05_14_covid_rapid_test_reliability_files/figure-html/unnamed-chunk-4-1.png" width="672" />
This plot shows that <code>viral_load</code> is directly derived from the <code>ct_value</code> through a calibration factor.
PCR Ct values of &gt; 35 are considered as the threshold value for detecting a COVID infection using the PCR test, so the values in this plot make sense for COVID positive samples.</p>
<p>Take some time to appreciate the huge range difference in the samples on display here.
From only 10.000 viral particles (<span class="math inline">\(log_{10}{(10^4)} = 4\)</span> ) to almost 1 billion (<span class="math inline">\(log_{10}{(10^9)} = 9\)</span> ) particles.</p>
<p>We can also see that apparently, there were two separate PCR assays (test types), each with a separate conversion formula used to obtain the estimated viral load.</p>
<p>(<strong>N.b.</strong> The missings for <code>pcr_assay_type</code> are because for two of three datasets, it was difficult to extract this information from the PDF file. From the plot, we can conclude that for these datasets, the same two assays were used since the values map onto the same two calibration lines)</p>
</div>
<div id="sensitivity-of-the-antigen-test" class="section level2">
<h2>Sensitivity of the Antigen test</h2>
<p>The dataset contains all samples for which the PCR test was positive.
Let’s start by checking the raw percentage of antigen test measurements that are positive as well.
This is called the <strong>sensitivity</strong> of a test.</p>
<pre class="r"><code>res &lt;- df_pcr_pos %&gt;%
  summarize(sensitivity = mean(mm_value), 
            N = n())

res</code></pre>
<pre><code>## # A tibble: 1 x 2
##   sensitivity     N
##         &lt;dbl&gt; &lt;int&gt;
## 1       0.792   120</code></pre>
<p>So for all PCR positive samples, 79.2 % is positive as well.
This means that, on average, if we would use the antigen test kit, we have a one in five (20%) probability of not detecting COVID-19, compared to when we would have used the method used by test centers operated by the public health agencies.</p>
<p>This value is slightly lower, but close to what is mentioned in the Roche kit’s leaflet.</p>
<p>Let’s postpone evaluation of this fact for a moment and look a bit closer at the data.
For example, we can example the relationship between <code>viral_load</code> and a positive antigen test result (<code>mm_value</code> = 1):</p>
<pre class="r"><code>set.seed(123)
ggplot(df_pcr_pos, aes(x = viral_load, y = mm_value)) + 
  geom_jitter(height = 0.1) +
  geom_smooth() + 
  geom_vline(xintercept = c(5.7, 7), col = &quot;red&quot;)</code></pre>
<p><img src="/post/2021_05_14_covid_rapid_test_reliability_files/figure-html/unnamed-chunk-6-1.png" width="672" />
From this plot, we can see that the probability of obtaining a false negative result (<code>mm_value</code> of 0) on the antigen test decreases as the viral load <strong>of the PCR sample</strong> increases.</p>
<p>From the data we also see that before the antigen test to work about half of the time (blue line at 0.5), the PCR sample needs to contain around <span class="math inline">\(5 \cdot 10^5\)</span> viral particles (log10 scale 5.7), and for it to work reliably, we need around <span class="math inline">\(10^7\)</span> particles (“high” viral load) in the PCR sample (which is a combination of <strong>oropharyngeal and nasopharyngeal swab</strong>). This last bit is important: the researchers did not measure the viral load in the nasal swabs used for the antigen test, these are likely different.</p>
<p>For really high viral loads, above <span class="math inline">\(10^7\)</span> particles in the <strong>NP/OP sample</strong>, the probability of a false negative result is only a few percent:</p>
<pre class="r"><code>df_pcr_pos %&gt;% filter(viral_load &gt;= 7) %&gt;%
  summarize(sensitivity = mean(mm_value), 
            N = n())</code></pre>
<pre><code>## # A tibble: 1 x 2
##   sensitivity     N
##         &lt;dbl&gt; &lt;int&gt;
## 1       0.972    71</code></pre>
</div>
</div>
<div id="viral-loads-varies-with-days-of-symptoms" class="section level1">
<h1>Viral loads varies with days of symptoms</h1>
<p>Above, we already discussed that the viral load varies with the time since infection.</p>
<p>If we want to use the antigen test <strong>instead</strong> of taking a PCR test, we don’t have information on the viral load. What we often do have is the days since symptoms, and we know that in the first few days of symptoms viral load is highest.</p>
<p>We can check this by plotting the <code>days_of_symptoms</code> versus <code>viral_load</code>:</p>
<pre class="r"><code>ggplot(df_pcr_pos, aes(x = days_of_symptoms, y = viral_load)) + 
  geom_smooth() + expand_limits(x = -4) + geom_vline(xintercept = 1, linetype = &quot;dashed&quot;) +
  geom_vline(xintercept = c(3, 7), col = &quot;red&quot;) + geom_hline(yintercept = 7, col = &quot;grey&quot;, linetype = &quot;dashed&quot;) +
  geom_jitter(height = 0, width = 0.2) </code></pre>
<p><img src="/post/2021_05_14_covid_rapid_test_reliability_files/figure-html/unnamed-chunk-8-1.png" width="672" />
From this plot, we learn that the viral load is highest on the onset of symptoms day (typically 5 days after infection) and decreases afterwards.</p>
<p>Above, we saw that the sensitivity in the whole sample was not equal to the sensitivity mentioned in the leaflet.
When evaluating rapid antigen tests, sometimes thresholds for days of symptoms are used, for example &lt;= 3 days or &lt;= 7 days (plotted in red).</p>
<p>For the sensitivity in the leaflet, a threshold of &lt;= 7 days was used on the days of symptoms.</p>
<p>Let us see how sensitive the antigen test is for these subgroups:</p>
<pre class="r"><code>res &lt;- df_pcr_pos %&gt;%
  filter(days_of_symptoms &lt;= 3) %&gt;%
  summarize(label = &quot;&lt; 3 days&quot;,
            sensitivity = mean(mm_value), 
            N = n())

res2 &lt;- df_pcr_pos %&gt;%
  filter(days_of_symptoms &lt;= 7) %&gt;%
  summarize(label = &quot;&lt; 7 days&quot;,
            sensitivity = mean(mm_value), 
            N = n())

bind_rows(res, res2)</code></pre>
<pre><code>## # A tibble: 2 x 3
##   label    sensitivity     N
##   &lt;chr&gt;          &lt;dbl&gt; &lt;int&gt;
## 1 &lt; 3 days       0.857    49
## 2 &lt; 7 days       0.85    100</code></pre>
<p>The sensitivity in both subgroups is increased to 85.7 % and 85 %.
Now only 1 in 7 cases is missed by the antigen test.
This sensitivity is now very close to that in the leaflet. The dataset in the leaflet has N = 102, whereas here we have N = 100.
Given that the difference is very small, I decided to not look into this any further.</p>
</div>
<div id="the-swab-effect-going-bayesian" class="section level1">
<h1>The swab effect: going Bayesian</h1>
<p>Ok, so the rapid antigen test is less sensitive than PCR.
What about the effect of using self-administered nasal swabs, versus professional health workers taking a nasopharyngeal swab (and often a swab in the back of the throat as well)?</p>
<p>Lucky for us, there exists also a version of the Roche rapid antigen kit that comes with nasopharyngeal swabs.
And a recent Dutch study, with samples from a test center in Rotterdam, used this kit (ref: Igloi et al 2021).</p>
<p>Cool! This allows us to get an estimate of the “swab” effect. Lets try and create two comparable groups in both studies so we can compare the sensitivity.</p>
<p>The Igloi et al. paper reports results for a particular subset that we can also create in the Berlin dataset.
They report that for the subset of samples with high viral load (viral load <span class="math inline">\(2.17 \cdot 10^5\)</span> particles / ml = 5.35 on the log10 scale) <strong>AND</strong> who presented within 7 days of symptom onset, they found a sensitivity of 95.8% (CI95% 90.5-98.2). The percentage is based on N = 640 persons.</p>
<p>We can check what the sensitivity is for this subgroup in the Berlin dataset:</p>
<pre class="r"><code>df_pcr_pos %&gt;% filter(viral_load &gt;= 5.35 &amp; days_of_symptoms &lt;= 7) %&gt;%
  summarize(sensitivity = mean(mm_value), 
            N = n())</code></pre>
<pre><code>## # A tibble: 1 x 2
##   sensitivity     N
##         &lt;dbl&gt; &lt;int&gt;
## 1       0.898    88</code></pre>
<p>In the same subgroup of high viral load, sensitivity of the nasal swab test is 6% lower than the nasopharyngeal swab test. But how do we have to weigh this evidence? N = 88 is not so much data.</p>
<p>Here, we go Bayesian. What is a reasonable difference to expect, or in bayesian terminology: what is our <strong>prior</strong> here? Enter domain knowledge.</p>
<p>From the literature, both the recent literature on COVID-19 testing, but also the older literature on Influenza swabbing, I estimate that self-collected nasal swabs are roughly 10% less accurate than nasopharyngeal swabs.
For example, from the meta-analysis of Seaman <em>et al.</em> (2019):</p>
<p><em>Although nasopharyngeal/nasal wash aspirates and nasopharyngeal (NP) swabs are considered the optimal sampling technique for the confirmation of influenza [3,10,11], neither is reliably self-collected</em></p>
<p><em>Pooled sensitivity was 87% (95%CI:80%,92%) and specificity was 99% (95%CI:98%,100%), compared to professional-collected swabs in the diagnosis of influenza.</em></p>
<p>A recent systematic review on the various ways to “obtain a COVID-19 specimen” (Lee et al) found that</p>
<p><em>Three specimen types captured lower % positives (Nasal Swabs [82%, 95% CI: 73 to 90%], oropharyngeal swabs [84%, 95% CI: 57 to 100%], and saliva [88%, 95% CI: 81 to 93%]) than nasopharyngeal swabs</em></p>
<p>We can use simulation to get a distribution of plausible values for the sensitivity in the Berlin subset, <strong>assuming that the true sensitivity is 85%</strong>.</p>
<pre class="r"><code>set.seed(123)
sample_size = 88
prior_probability = 0.85

est_p &lt;- rbinom(10000, sample_size, p=prior_probability)/sample_size

ggplot(data.frame(est_p), aes(x = est_p)) +
  geom_histogram() +
  geom_vline(xintercept = 0.898, linetype = &quot;dashed&quot;, col= &quot;red&quot;)</code></pre>
<p><img src="/post/2021_05_14_covid_rapid_test_reliability_files/figure-html/unnamed-chunk-11-1.png" width="672" />
We can see that the observed outcome in the Berlin dataset is consistent with our domain knowledge, falling into a high probability range of likely outcomes. The outcome of this experiment would cause us to slightly update our beliefs towards a higher probability, say maybe 86% or so.</p>
<p>So to conclude: a sizable portion of the reduction in sensitivity of the antigen test versus PCR test is caused by the way the sample is taken, <strong>the swab effect</strong>, not by using a different measurement technique (PCR vs flow test)!</p>
</div>
<div id="that-other-metric-the-specificity" class="section level1">
<h1>That other metric: the specificity</h1>
<p>So far, the discussion centered around the <strong>sensitivity</strong> of the test.
Equally important is the <strong>specificity</strong> of the test. This quantifies if the test result of the antigen test is specific for COVID-19. It would be bad if the test would also show a result for other viruses, or even unrelated molecules.</p>
<p>To examine this, we use the aggregated data supplied on the leaflet from the kit, <code>df_leaflet</code>.</p>
<p><strong>N.b.</strong> The aggregated data is a subset of all the data from the three studies, because the data was subsetted for cases with <code>&lt;= 7 days_of_symptoms</code>.</p>
<p>This dataset contains for each sample one of four possibilities:</p>
<ul>
<li>Both tests are negative,</li>
<li>both tests are positive,</li>
<li>the PCR test is positive but the antigen test negative,</li>
<li>the PCR test is negative but the antigen positive.</li>
</ul>
<p>We use the <code>yardstick</code> package of R’s <code>tidymodels</code> family to create the 2x2 table and analyze the specificity.</p>
<p>(<strong>Overthinking</strong>: Note that the <code>yardstick</code> package is used to quantify the performance of statistical prediction models by comparing the model predictions to the true values contained in the training data. This provides us with an analogy where the antigen test can be viewed as a model that is trying the predict the outcome of the PCR test.)</p>
<pre class="r"><code>options(yardstick.event_first = FALSE)

conf_matrix &lt;- yardstick::conf_mat(df_leaflet, pcr_result, ag_result)

autoplot(conf_matrix, 
         type = &quot;heatmap&quot;, 
         title = &quot;Truth = PCR test, Prediction = Antigen test&quot;)</code></pre>
<p><img src="/post/2021_05_14_covid_rapid_test_reliability_files/figure-html/unnamed-chunk-12-1.png" width="288" />
From the heatmap (confusingly called a confusion matrix among ML practioners), we see that:</p>
<ul>
<li>For most samples (N = 431), both tests are COVID-19 negative.</li>
<li>85 + 17 = 102 samples tested COVID-19 positive using the PCR-test</li>
<li>85 out of 102 samples that are PCR positive, are antigen test positive as well</li>
</ul>
<p>For the specificity, we have to look at the samples where the PCR test is negative, but the antigen test is positive, and compare these to all the samples that are PCR-test negative. These are the number of tests where the antigen test picked up a non-specific signal. One minus this percentage gives the specificity (1 - 4/435 = 431/435):</p>
<pre class="r"><code>yardstick::spec(df_leaflet, pcr_result, ag_result)</code></pre>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 spec    binary         0.991</code></pre>
<p>Thus, we find that the antigen test is highly specific, with around 1% of false positives.</p>
</div>
<div id="uncertainty-in-the-estimated-specificity-and-sensitivity" class="section level1">
<h1>Uncertainty in the estimated specificity and sensitivity</h1>
<p>So far, we did not discuss the sampling variability in the estimated specificity and sensitivity.</p>
<p>The kit leaflet mentions the following confidence intervals:</p>
<ul>
<li>Sensitivity 83.3% (95%CI: 74.7% - 90.0%)</li>
<li>Specificity 99.1% (95%CI: 97.7% - 99.7%)</li>
</ul>
<p>The R-package <code>yardstick</code> does not yet include confidence intervals, so I generated these using bootstrapping. I calculate both metrics for 10.000 samples sampled from the raw data. For brevity I omitted the code here, go check out my <a href="https://github.com/gsverhoeven/hugo_source/tree/master/content/post/sars_test">Github</a> for the R script.</p>
<p>The bootstrapping approach yields the following range of plausible values given the data (95% interval):</p>
<pre class="r"><code>quantile(spec_vec, probs = c(0.025, 0.975))</code></pre>
<pre><code>##      2.5%     97.5% 
## 0.9811765 0.9977477</code></pre>
<pre class="r"><code>quantile(sens_vec, probs = c(0.025, 0.975))</code></pre>
<pre><code>##      2.5%     97.5% 
## 0.7570030 0.9029126</code></pre>
<p>The amount of data (N = 537) prevents us from getting an exact match to the leaflet’s confidence intervals, that are based on theoretic formulas. But we do get pretty close.</p>
<p>Especially for the sensitivity, there is quite some uncertainty, we see that plausible values range from 76% up to 90% <em>for this particular cohort of cases with this particular mix of viral loads that showed up during the last four months of 2020 in the University hospital in Berlin</em>.</p>
</div>
<div id="conclusions" class="section level1">
<h1>Conclusions</h1>
<p>To summarise: we found that the numbers of the kit’s leaflet are reliable, reproducible, and published in full detail in the scientific literature.
Hurray!</p>
<p>We also found that even the gold standard PCR is not able to detect all infected persons, it all depends on how much virus is present, and how the sample is obtained.</p>
<p>But all in all, the PCR test is clearly more accurate. Why would we want to use an antigen test then?
To do the PCR test you need a lab with skilled people, equipment such as PCR devices and pipets, and time, as the process takes at least a few hours to complete. The advantage of an antigen test is to have a low-tech, faster alternative that can be self-administered. But that comes at a cost, because the antigen tests are less sensitive.</p>
<p>From the analysis, it is clear that the rapid Antigen tests need more virus present to reliably detect infection. It is ALSO clear that the test is highly specific, with less than 1% false positives. Note that a false positive rate of 1% still means that in a healthy population of 1000, 10 are falsely detected as having COVID-19.
Finally, we find that the nasal swabs are less sensitive than the nasopharyngeal (“deep nose”) swabs, this reduces sensitivity by roughly 10% (Lindner <em>et al.</em> 2021, Igloi <em>et al.</em> 2021, Lee <em>et al.</em> 2021).</p>
<p>So both the measurement device, and the self-collection of sample contribute to reduce the sensitivity. But now comes the key insight: the persons that produce the largest amounts of virus get detected, irrespective of whether they have symptoms or not. To me, this seems like a “Unique Selling Point” of the rapid tests: the ability to rapidly detect the most contagious persons in a group, after which these persons can go into quarantine and help reduce spread.</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<ul>
<li><p><em>Head-to-head comparison of SARS-CoV-2 antigen-detecting rapid test with self-collected nasal swab versus professional-collected nasopharyngeal swab</em>:
Andreas K. Lindner, Olga Nikolai, Franka Kausch, Mia Wintel, Franziska Hommes, Maximilian Gertler, Lisa J. Krüger, Mary Gaeddert, Frank Tobian, Federica Lainati, Lisa Köppel, Joachim Seybold, Victor M. Corman, Christian Drosten, Jörg Hofmann, Jilian A. Sacks, Frank P. Mockenhaupt, Claudia M. Denkinger, <a href="https://erj.ersjournals.com/content/57/4/2003961">European Respiratory Journal 2021 57: 2003961</a></p></li>
<li><p><em>Head-to-head comparison of SARS-CoV-2 antigen-detecting rapid test with professional-collected nasal versus nasopharyngeal swab</em>:
Andreas K. Lindner, Olga Nikolai, Chiara Rohardt, Susen Burock, Claudia Hülso, Alisa Bölke, Maximilian Gertler, Lisa J. Krüger, Mary Gaeddert, Frank Tobian, Federica Lainati, Joachim Seybold, Terry C. Jones, Jörg Hofmann, Jilian A. Sacks, Frank P. Mockenhaupt, Claudia M. Denkinger <a href="https://erj.ersjournals.com/content/57/5/2004430">European Respiratory Journal 2021 57: 2004430</a></p></li>
<li><p><em>SARS-CoV-2 patient self-testing with an antigen-detecting rapid test: a head-to-head comparison with professional testing</em>:
Andreas K. Lindner, Olga Nikolai, Chiara Rohardt, Franka Kausch, Mia Wintel, Maximilian Gertler, Susen Burock, Merle Hörig, Julian Bernhard, Frank Tobian, Mary Gaeddert, Federica Lainati, Victor M. Corman, Terry C. Jones, Jilian A. Sacks, Joachim Seybold, Claudia M. Denkinger, Frank P. Mockenhaupt, under review, <a href="https://www.medrxiv.org/content/10.1101/2021.01.06.20249009v1">preprint on medrxiv.org</a></p></li>
<li><p><em>Variation in False-Negative Rate of Reverse Transcriptase Polymerase Chain Reaction–Based SARS-CoV-2 Tests by Time Since Exposure</em>: Lauren M. Kucirka, Stephen A. Lauer, Oliver Laeyendecker, Denali Boon, Justin Lessler <a href="https://www.acpjournals.org/doi/full/10.7326/M20-1495">Link to paper</a></p></li>
<li><p><em>Clinical evaluation of the Roche/SD Biosensor rapid antigen test with symptomatic, non-hospitalized patients in a municipal health service drive-through testing site</em>:
Zsὁfia Iglὁi, Jans Velzing, Janko van Beek, David van de Vijver, Georgina Aron, Roel Ensing, KimberleyBenschop, Wanda Han, Timo Boelsums, Marion Koopmans, Corine Geurtsvankessel, Richard Molenkamp <a href="https://www.medrxiv.org/content/10.1101/2020.11.18.20234104v1">Link on medrxiv.org</a></p></li>
<li><p><em>Performance of Saliva, Oropharyngeal Swabs, and Nasal Swabs for SARS-CoV-2 Molecular Detection: a Systematic Review and Meta-analysis</em>:
Rose A. Lee, Joshua C. Herigona, Andrea Benedetti, Nira R. Pollock, Claudia M. Denkinger <a href="https://journals.asm.org/doi/10.1128/JCM.02881-20">Link to paper</a></p></li>
<li><p><em>Self-collected compared with professional-collected swabbing in the diagnosis of influenza in symptomatic individuals: A meta-analysis and assessment of validity</em>:
Seaman et al 2019 <a href="https://pubmed.ncbi.nlm.nih.gov/31400670/">Link to paper</a></p></li>
</ul>
</div>

    </div>

    





<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/covid-19-dag-causal-graph-bayesian-statistics/">COVID-19, DAG, causal graph, bayesian statistics</a>
  
</div>



<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/post/covid_antigen_test_reliability/&amp;text=Using%20R%20to%20analyse%20the%20Roche%20Antigen%20Rapid%20Test:%20How%20accurate%20is%20it?" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/post/covid_antigen_test_reliability/&amp;t=Using%20R%20to%20analyse%20the%20Roche%20Antigen%20Rapid%20Test:%20How%20accurate%20is%20it?" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Using%20R%20to%20analyse%20the%20Roche%20Antigen%20Rapid%20Test:%20How%20accurate%20is%20it?&amp;body=/post/covid_antigen_test_reliability/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/post/covid_antigen_test_reliability/&amp;title=Using%20R%20to%20analyse%20the%20Roche%20Antigen%20Rapid%20Test:%20How%20accurate%20is%20it?" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Using%20R%20to%20analyse%20the%20Roche%20Antigen%20Rapid%20Test:%20How%20accurate%20is%20it?%20/post/covid_antigen_test_reliability/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/post/covid_antigen_test_reliability/&amp;title=Using%20R%20to%20analyse%20the%20Roche%20Antigen%20Rapid%20Test:%20How%20accurate%20is%20it?" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>












  






  
  
  
    
  
  
  <div class="media author-card content-widget-hr">
    
      
      <img class="portrait mr-3" src="/authors/admin/avatar_hudb6f5a71508eb5317c72df2dc43608d9_19467_250x250_fill_q90_lanczos_center.jpg" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title"><a href="/">Gertjan Verhoeven</a></h5>
      <h6 class="card-subtitle">Data Scientist / Policy Advisor</h6>
      <p class="card-text">Gertjan Verhoeven is a research scientist currently at the Dutch Healthcare Authority, working on health policy and statistical methods.</p>
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="/#contact" >
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://twitter.com/GertjanVerhoev1" target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://scholar.google.nl/citations?user=B-tEtToAAAAJ&amp;hl=nl" target="_blank" rel="noopener">
        <i class="ai ai-google-scholar"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/gsverhoeven" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://stackoverflow.com/users/10628316/gertjan-verhoeven" target="_blank" rel="noopener">
        <i class="fab fa-stack-overflow"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>









  
  



  </div>
</article>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.3/mermaid.min.js" integrity="" crossorigin="anonymous" title="mermaid"></script>
      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js" integrity="sha256-1zu+3BnLYV9LdiY85uXMzii3bdrkelyp37e0ZyTAQh0=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/r.min.js"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/python.min.js"></script>
        
      

    

    
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.a0d331bcd05dbe8b31e244f796710f08.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  

  <p class="powered-by">
    © 2019, 2020 &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
